/*
 * generated by Xtext
 */
package org.osate.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.osate.xtext.ui.internal.BaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BaActivator.getInstance().getInjector(BaActivator.ORG_OSATE_XTEXT_BA);
	}
	
}
