/*
 * generated by Xtext
 */
package org.osate.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.osate.xtext.services.BaGrammarAccess;

public class BaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.osate.xtext.parser.antlr.internal.InternalBaParser createParser(XtextTokenStream stream) {
		return new org.osate.xtext.parser.antlr.internal.InternalBaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AnnexSubclause";
	}
	
	public BaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
