/*
 * generated by Xtext
 */
package org.osate.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.osate.xtext.services.BaGrammarAccess;

public class BaParser extends AbstractContentAssistParser {
	
	@Inject
	private BaGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.osate.xtext.ui.contentassist.antlr.internal.InternalBaParser createParser() {
		org.osate.xtext.ui.contentassist.antlr.internal.InternalBaParser result = new org.osate.xtext.ui.contentassist.antlr.internal.InternalBaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBehaviorActionsAccess().getAlternatives(), "rule__BehaviorActions__Alternatives");
					put(grammarAccess.getBehaviorActionAccess().getAlternatives(), "rule__BehaviorAction__Alternatives");
					put(grammarAccess.getBasicActionAccess().getAlternatives(), "rule__BasicAction__Alternatives");
					put(grammarAccess.getAssignmentActionAccess().getAlternatives_2(), "rule__AssignmentAction__Alternatives_2");
					put(grammarAccess.getCommunicationActionAccess().getAlternatives(), "rule__CommunicationAction__Alternatives");
					put(grammarAccess.getCommunicationActionAccess().getAlternatives_1_1(), "rule__CommunicationAction__Alternatives_1_1");
					put(grammarAccess.getCommunicationActionAccess().getAlternatives_2(), "rule__CommunicationAction__Alternatives_2");
					put(grammarAccess.getIfStatementAccess().getAlternatives_5(), "rule__IfStatement__Alternatives_5");
					put(grammarAccess.getForOrForAllStatementAccess().getAlternatives_0(), "rule__ForOrForAllStatement__Alternatives_0");
					put(grammarAccess.getElementValuesAccess().getAlternatives(), "rule__ElementValues__Alternatives");
					put(grammarAccess.getWhileOrDoUntilStatementAccess().getAlternatives(), "rule__WhileOrDoUntilStatement__Alternatives");
					put(grammarAccess.getFactorAccess().getAlternatives(), "rule__Factor__Alternatives");
					put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
					put(grammarAccess.getValueVariableAccess().getAlternatives(), "rule__ValueVariable__Alternatives");
					put(grammarAccess.getValueConstantAccess().getAlternatives(), "rule__ValueConstant__Alternatives");
					put(grammarAccess.getBehaviorBooleanLiteralAccess().getAlternatives_1(), "rule__BehaviorBooleanLiteral__Alternatives_1");
					put(grammarAccess.getPropertyReferenceAccess().getAlternatives_0(), "rule__PropertyReference__Alternatives_0");
					put(grammarAccess.getPropertyReferenceAccess().getAlternatives_0_1_0(), "rule__PropertyReference__Alternatives_0_1_0");
					put(grammarAccess.getPropertyNameAccess().getAlternatives_1(), "rule__PropertyName__Alternatives_1");
					put(grammarAccess.getPropertyNameAccess().getAlternatives_1_1_1(), "rule__PropertyName__Alternatives_1_1_1");
					put(grammarAccess.getIntegerValueAccess().getAlternatives(), "rule__IntegerValue__Alternatives");
					put(grammarAccess.getIntegerValueConstantAccess().getAlternatives(), "rule__IntegerValueConstant__Alternatives");
					put(grammarAccess.getBehaviorConditionAccess().getAlternatives(), "rule__BehaviorCondition__Alternatives");
					put(grammarAccess.getExecuteConditionAccess().getAlternatives(), "rule__ExecuteCondition__Alternatives");
					put(grammarAccess.getDispatchConditionAccess().getAlternatives_3(), "rule__DispatchCondition__Alternatives_3");
					put(grammarAccess.getContainedPropertyAssociationAccess().getAlternatives_1(), "rule__ContainedPropertyAssociation__Alternatives_1");
					put(grammarAccess.getPropertyAssociationAccess().getAlternatives_1(), "rule__PropertyAssociation__Alternatives_1");
					put(grammarAccess.getPropertyExpressionAccess().getAlternatives(), "rule__PropertyExpression__Alternatives");
					put(grammarAccess.getBooleanLiteralAccess().getAlternatives_1(), "rule__BooleanLiteral__Alternatives_1");
					put(grammarAccess.getPlusMinusAccess().getAlternatives(), "rule__PlusMinus__Alternatives");
					put(grammarAccess.getSignedIntAccess().getAlternatives_0(), "rule__SignedInt__Alternatives_0");
					put(grammarAccess.getSignedRealAccess().getAlternatives_0(), "rule__SignedReal__Alternatives_0");
					put(grammarAccess.getNumAltAccess().getAlternatives(), "rule__NumAlt__Alternatives");
					put(grammarAccess.getMultiplyingOperatorAccess().getAlternatives(), "rule__MultiplyingOperator__Alternatives");
					put(grammarAccess.getBinaryAddingOperatorAccess().getAlternatives(), "rule__BinaryAddingOperator__Alternatives");
					put(grammarAccess.getLogicalOperatorAccess().getAlternatives(), "rule__LogicalOperator__Alternatives");
					put(grammarAccess.getRelationalOperatorAccess().getAlternatives(), "rule__RelationalOperator__Alternatives");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getGroup(), "rule__BehaviorAnnexSubclause__Group__0");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getGroup_1(), "rule__BehaviorAnnexSubclause__Group_1__0");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getGroup_1_1(), "rule__BehaviorAnnexSubclause__Group_1_1__0");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getGroup_1_1_1(), "rule__BehaviorAnnexSubclause__Group_1_1_1__0");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getGroup_3(), "rule__BehaviorAnnexSubclause__Group_3__0");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getGroup_3_1(), "rule__BehaviorAnnexSubclause__Group_3_1__0");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getGroup_5(), "rule__BehaviorAnnexSubclause__Group_5__0");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getGroup_5_1(), "rule__BehaviorAnnexSubclause__Group_5_1__0");
					put(grammarAccess.getBehaviorVariableSetAccess().getGroup(), "rule__BehaviorVariableSet__Group__0");
					put(grammarAccess.getBehaviorVariableSetAccess().getGroup_1(), "rule__BehaviorVariableSet__Group_1__0");
					put(grammarAccess.getBehaviorVariableSetAccess().getGroup_4(), "rule__BehaviorVariableSet__Group_4__0");
					put(grammarAccess.getBehaviorStateSetAccess().getGroup(), "rule__BehaviorStateSet__Group__0");
					put(grammarAccess.getBehaviorStateSetAccess().getGroup_1(), "rule__BehaviorStateSet__Group_1__0");
					put(grammarAccess.getBehaviorTransitionAccess().getGroup(), "rule__BehaviorTransition__Group__0");
					put(grammarAccess.getBehaviorTransitionAccess().getGroup_0(), "rule__BehaviorTransition__Group_0__0");
					put(grammarAccess.getBehaviorTransitionAccess().getGroup_0_1(), "rule__BehaviorTransition__Group_0_1__0");
					put(grammarAccess.getBehaviorTransitionAccess().getGroup_2(), "rule__BehaviorTransition__Group_2__0");
					put(grammarAccess.getBehaviorActionBlockAccess().getGroup(), "rule__BehaviorActionBlock__Group__0");
					put(grammarAccess.getBehaviorActionBlockAccess().getGroup_3(), "rule__BehaviorActionBlock__Group_3__0");
					put(grammarAccess.getBehaviorActionSequenceAccess().getGroup(), "rule__BehaviorActionSequence__Group__0");
					put(grammarAccess.getBehaviorActionSequenceAccess().getGroup_0(), "rule__BehaviorActionSequence__Group_0__0");
					put(grammarAccess.getBehaviorActionSetAccess().getGroup(), "rule__BehaviorActionSet__Group__0");
					put(grammarAccess.getBehaviorActionSetAccess().getGroup_0(), "rule__BehaviorActionSet__Group_0__0");
					put(grammarAccess.getAssignmentActionAccess().getGroup(), "rule__AssignmentAction__Group__0");
					put(grammarAccess.getAnyAccess().getGroup(), "rule__Any__Group__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_0(), "rule__CommunicationAction__Group_0__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_0_2(), "rule__CommunicationAction__Group_0_2__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_0_2_2(), "rule__CommunicationAction__Group_0_2_2__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_1(), "rule__CommunicationAction__Group_1__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_1_1_0(), "rule__CommunicationAction__Group_1_1_0__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_1_1_0_1(), "rule__CommunicationAction__Group_1_1_0_1__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_1_1_4(), "rule__CommunicationAction__Group_1_1_4__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_1_1_4_1(), "rule__CommunicationAction__Group_1_1_4_1__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_1_1_4_1_2(), "rule__CommunicationAction__Group_1_1_4_1_2__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_1_1_5(), "rule__CommunicationAction__Group_1_1_5__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_1_1_5_1(), "rule__CommunicationAction__Group_1_1_5_1__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_1_1_6(), "rule__CommunicationAction__Group_1_1_6__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_1_1_6_1(), "rule__CommunicationAction__Group_1_1_6_1__0");
					put(grammarAccess.getCommunicationActionAccess().getGroup_1_1_6_1_2(), "rule__CommunicationAction__Group_1_1_6_1_2__0");
					put(grammarAccess.getQualifiedNamedElementAccess().getGroup(), "rule__QualifiedNamedElement__Group__0");
					put(grammarAccess.getNameSpaceAccess().getGroup(), "rule__NameSpace__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getReferenceAccess().getGroup_1(), "rule__Reference__Group_1__0");
					put(grammarAccess.getArrayIdentifierAccess().getGroup(), "rule__ArrayIdentifier__Group__0");
					put(grammarAccess.getArrayIdentifierAccess().getGroup_1(), "rule__ArrayIdentifier__Group_1__0");
					put(grammarAccess.getTimedActionAccess().getGroup(), "rule__TimedAction__Group__0");
					put(grammarAccess.getTimedActionAccess().getGroup_3(), "rule__TimedAction__Group_3__0");
					put(grammarAccess.getTimedActionAccess().getGroup_5(), "rule__TimedAction__Group_5__0");
					put(grammarAccess.getTimedActionAccess().getGroup_5_3(), "rule__TimedAction__Group_5_3__0");
					put(grammarAccess.getIfStatementAccess().getGroup(), "rule__IfStatement__Group__0");
					put(grammarAccess.getElseIfStatementAccess().getGroup(), "rule__ElseIfStatement__Group__0");
					put(grammarAccess.getElseStatementAccess().getGroup(), "rule__ElseStatement__Group__0");
					put(grammarAccess.getForOrForAllStatementAccess().getGroup(), "rule__ForOrForAllStatement__Group__0");
					put(grammarAccess.getIterativeVariableAccess().getGroup(), "rule__IterativeVariable__Group__0");
					put(grammarAccess.getWhileOrDoUntilStatementAccess().getGroup_0(), "rule__WhileOrDoUntilStatement__Group_0__0");
					put(grammarAccess.getWhileOrDoUntilStatementAccess().getGroup_1(), "rule__WhileOrDoUntilStatement__Group_1__0");
					put(grammarAccess.getValueExpressionAccess().getGroup(), "rule__ValueExpression__Group__0");
					put(grammarAccess.getValueExpressionAccess().getGroup_1(), "rule__ValueExpression__Group_1__0");
					put(grammarAccess.getRelationAccess().getGroup(), "rule__Relation__Group__0");
					put(grammarAccess.getRelationAccess().getGroup_1(), "rule__Relation__Group_1__0");
					put(grammarAccess.getSimpleExpressionAccess().getGroup(), "rule__SimpleExpression__Group__0");
					put(grammarAccess.getSimpleExpressionAccess().getGroup_2(), "rule__SimpleExpression__Group_2__0");
					put(grammarAccess.getTermAccess().getGroup(), "rule__Term__Group__0");
					put(grammarAccess.getTermAccess().getGroup_1(), "rule__Term__Group_1__0");
					put(grammarAccess.getFactorAccess().getGroup_0(), "rule__Factor__Group_0__0");
					put(grammarAccess.getFactorAccess().getGroup_0_1(), "rule__Factor__Group_0_1__0");
					put(grammarAccess.getFactorAccess().getGroup_1(), "rule__Factor__Group_1__0");
					put(grammarAccess.getFactorAccess().getGroup_2(), "rule__Factor__Group_2__0");
					put(grammarAccess.getValueAccess().getGroup_2(), "rule__Value__Group_2__0");
					put(grammarAccess.getPortDequeueValueAccess().getGroup(), "rule__PortDequeueValue__Group__0");
					put(grammarAccess.getPortCountValueAccess().getGroup(), "rule__PortCountValue__Group__0");
					put(grammarAccess.getPortFreshValueAccess().getGroup(), "rule__PortFreshValue__Group__0");
					put(grammarAccess.getBehaviorNumericLiteralAccess().getGroup(), "rule__BehaviorNumericLiteral__Group__0");
					put(grammarAccess.getBehaviorBooleanLiteralAccess().getGroup(), "rule__BehaviorBooleanLiteral__Group__0");
					put(grammarAccess.getPropertyReferenceAccess().getGroup(), "rule__PropertyReference__Group__0");
					put(grammarAccess.getPropertyReferenceAccess().getGroup_0_0(), "rule__PropertyReference__Group_0_0__0");
					put(grammarAccess.getPropertyReferenceAccess().getGroup_0_1(), "rule__PropertyReference__Group_0_1__0");
					put(grammarAccess.getPropertyReferenceAccess().getGroup_2(), "rule__PropertyReference__Group_2__0");
					put(grammarAccess.getPropertyNameAccess().getGroup(), "rule__PropertyName__Group__0");
					put(grammarAccess.getPropertyNameAccess().getGroup_1_0(), "rule__PropertyName__Group_1_0__0");
					put(grammarAccess.getPropertyNameAccess().getGroup_1_1(), "rule__PropertyName__Group_1_1__0");
					put(grammarAccess.getIntegerRangeAccess().getGroup(), "rule__IntegerRange__Group__0");
					put(grammarAccess.getBehaviorTimeAccess().getGroup(), "rule__BehaviorTime__Group__0");
					put(grammarAccess.getOthewiseConditionAccess().getGroup(), "rule__OthewiseCondition__Group__0");
					put(grammarAccess.getDispatchConditionAccess().getGroup(), "rule__DispatchCondition__Group__0");
					put(grammarAccess.getDispatchConditionAccess().getGroup_4(), "rule__DispatchCondition__Group_4__0");
					put(grammarAccess.getDispatchConditionAccess().getGroup_4_3(), "rule__DispatchCondition__Group_4_3__0");
					put(grammarAccess.getDispatchRelativeTimeoutCatchAccess().getGroup(), "rule__DispatchRelativeTimeoutCatch__Group__0");
					put(grammarAccess.getCompletionRelativeTimeoutCatchAccess().getGroup(), "rule__CompletionRelativeTimeoutCatch__Group__0");
					put(grammarAccess.getDispatchTriggerLogicalExpressionAccess().getGroup(), "rule__DispatchTriggerLogicalExpression__Group__0");
					put(grammarAccess.getDispatchTriggerLogicalExpressionAccess().getGroup_1(), "rule__DispatchTriggerLogicalExpression__Group_1__0");
					put(grammarAccess.getDispatchConjunctionAccess().getGroup(), "rule__DispatchConjunction__Group__0");
					put(grammarAccess.getDispatchConjunctionAccess().getGroup_1(), "rule__DispatchConjunction__Group_1__0");
					put(grammarAccess.getStopDispatchTriggerConditionAccess().getGroup(), "rule__StopDispatchTriggerCondition__Group__0");
					put(grammarAccess.getContainedPropertyAssociationAccess().getGroup(), "rule__ContainedPropertyAssociation__Group__0");
					put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_3(), "rule__ContainedPropertyAssociation__Group_3__0");
					put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_3_1(), "rule__ContainedPropertyAssociation__Group_3_1__0");
					put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_4(), "rule__ContainedPropertyAssociation__Group_4__0");
					put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_4_3(), "rule__ContainedPropertyAssociation__Group_4_3__0");
					put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_5(), "rule__ContainedPropertyAssociation__Group_5__0");
					put(grammarAccess.getPropertyAssociationAccess().getGroup(), "rule__PropertyAssociation__Group__0");
					put(grammarAccess.getPropertyAssociationAccess().getGroup_3(), "rule__PropertyAssociation__Group_3__0");
					put(grammarAccess.getPropertyAssociationAccess().getGroup_3_1(), "rule__PropertyAssociation__Group_3_1__0");
					put(grammarAccess.getPropertyAssociationAccess().getGroup_4(), "rule__PropertyAssociation__Group_4__0");
					put(grammarAccess.getBasicPropertyAssociationAccess().getGroup(), "rule__BasicPropertyAssociation__Group__0");
					put(grammarAccess.getModalPropertyValueAccess().getGroup(), "rule__ModalPropertyValue__Group__0");
					put(grammarAccess.getModalPropertyValueAccess().getGroup_5(), "rule__ModalPropertyValue__Group_5__0");
					put(grammarAccess.getOptionalModalPropertyValueAccess().getGroup(), "rule__OptionalModalPropertyValue__Group__0");
					put(grammarAccess.getOptionalModalPropertyValueAccess().getGroup_1(), "rule__OptionalModalPropertyValue__Group_1__0");
					put(grammarAccess.getOptionalModalPropertyValueAccess().getGroup_1_4(), "rule__OptionalModalPropertyValue__Group_1_4__0");
					put(grammarAccess.getBooleanLiteralAccess().getGroup(), "rule__BooleanLiteral__Group__0");
					put(grammarAccess.getReferenceTermAccess().getGroup(), "rule__ReferenceTerm__Group__0");
					put(grammarAccess.getRecordTermAccess().getGroup(), "rule__RecordTerm__Group__0");
					put(grammarAccess.getOldRecordTermAccess().getGroup(), "rule__OldRecordTerm__Group__0");
					put(grammarAccess.getComputedTermAccess().getGroup(), "rule__ComputedTerm__Group__0");
					put(grammarAccess.getComponentClassifierTermAccess().getGroup(), "rule__ComponentClassifierTerm__Group__0");
					put(grammarAccess.getListTermAccess().getGroup(), "rule__ListTerm__Group__0");
					put(grammarAccess.getListTermAccess().getGroup_2(), "rule__ListTerm__Group_2__0");
					put(grammarAccess.getListTermAccess().getGroup_2_1(), "rule__ListTerm__Group_2_1__0");
					put(grammarAccess.getFieldPropertyAssociationAccess().getGroup(), "rule__FieldPropertyAssociation__Group__0");
					put(grammarAccess.getContainmentPathElementAccess().getGroup(), "rule__ContainmentPathElement__Group__0");
					put(grammarAccess.getContainmentPathElementAccess().getGroup_0(), "rule__ContainmentPathElement__Group_0__0");
					put(grammarAccess.getContainmentPathElementAccess().getGroup_1(), "rule__ContainmentPathElement__Group_1__0");
					put(grammarAccess.getANNEXREFAccess().getGroup(), "rule__ANNEXREF__Group__0");
					put(grammarAccess.getArrayRangeAccess().getGroup(), "rule__ArrayRange__Group__0");
					put(grammarAccess.getArrayRangeAccess().getGroup_3(), "rule__ArrayRange__Group_3__0");
					put(grammarAccess.getSignedConstantAccess().getGroup(), "rule__SignedConstant__Group__0");
					put(grammarAccess.getIntegerTermAccess().getGroup(), "rule__IntegerTerm__Group__0");
					put(grammarAccess.getSignedIntAccess().getGroup(), "rule__SignedInt__Group__0");
					put(grammarAccess.getRealTermAccess().getGroup(), "rule__RealTerm__Group__0");
					put(grammarAccess.getSignedRealAccess().getGroup(), "rule__SignedReal__Group__0");
					put(grammarAccess.getNumericRangeTermAccess().getGroup(), "rule__NumericRangeTerm__Group__0");
					put(grammarAccess.getNumericRangeTermAccess().getGroup_3(), "rule__NumericRangeTerm__Group_3__0");
					put(grammarAccess.getQCLREFAccess().getGroup(), "rule__QCLREF__Group__0");
					put(grammarAccess.getQPREFAccess().getGroup(), "rule__QPREF__Group__0");
					put(grammarAccess.getQPREFAccess().getGroup_1(), "rule__QPREF__Group_1__0");
					put(grammarAccess.getQCREFAccess().getGroup(), "rule__QCREF__Group__0");
					put(grammarAccess.getQCREFAccess().getGroup_0(), "rule__QCREF__Group_0__0");
					put(grammarAccess.getQCREFAccess().getGroup_2(), "rule__QCREF__Group_2__0");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getVariablesAssignment_1_1_0(), "rule__BehaviorAnnexSubclause__VariablesAssignment_1_1_0");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getVariablesAssignment_1_1_1_1(), "rule__BehaviorAnnexSubclause__VariablesAssignment_1_1_1_1");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getStatesAssignment_3_0(), "rule__BehaviorAnnexSubclause__StatesAssignment_3_0");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getStatesAssignment_3_1_1(), "rule__BehaviorAnnexSubclause__StatesAssignment_3_1_1");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getTransitionsAssignment_5_0(), "rule__BehaviorAnnexSubclause__TransitionsAssignment_5_0");
					put(grammarAccess.getBehaviorAnnexSubclauseAccess().getTransitionsAssignment_5_1_1(), "rule__BehaviorAnnexSubclause__TransitionsAssignment_5_1_1");
					put(grammarAccess.getBehaviorVariableSetAccess().getVariablesAssignment_0(), "rule__BehaviorVariableSet__VariablesAssignment_0");
					put(grammarAccess.getBehaviorVariableSetAccess().getVariablesAssignment_1_1(), "rule__BehaviorVariableSet__VariablesAssignment_1_1");
					put(grammarAccess.getBehaviorVariableSetAccess().getDataClassifierAssignment_3(), "rule__BehaviorVariableSet__DataClassifierAssignment_3");
					put(grammarAccess.getBehaviorVariableAccess().getNameAssignment(), "rule__BehaviorVariable__NameAssignment");
					put(grammarAccess.getBehaviorStateSetAccess().getStatesAssignment_0(), "rule__BehaviorStateSet__StatesAssignment_0");
					put(grammarAccess.getBehaviorStateSetAccess().getStatesAssignment_1_1(), "rule__BehaviorStateSet__StatesAssignment_1_1");
					put(grammarAccess.getBehaviorStateSetAccess().getInitialAssignment_3(), "rule__BehaviorStateSet__InitialAssignment_3");
					put(grammarAccess.getBehaviorStateSetAccess().getCompleteAssignment_4(), "rule__BehaviorStateSet__CompleteAssignment_4");
					put(grammarAccess.getBehaviorStateSetAccess().getFinalAssignment_5(), "rule__BehaviorStateSet__FinalAssignment_5");
					put(grammarAccess.getBehaviorStateAccess().getNameAssignment(), "rule__BehaviorState__NameAssignment");
					put(grammarAccess.getBehaviorTransitionAccess().getNameAssignment_0_0(), "rule__BehaviorTransition__NameAssignment_0_0");
					put(grammarAccess.getBehaviorTransitionAccess().getPriorityAssignment_0_1_1(), "rule__BehaviorTransition__PriorityAssignment_0_1_1");
					put(grammarAccess.getBehaviorTransitionAccess().getSrcStatesAssignment_1(), "rule__BehaviorTransition__SrcStatesAssignment_1");
					put(grammarAccess.getBehaviorTransitionAccess().getSrcStatesAssignment_2_1(), "rule__BehaviorTransition__SrcStatesAssignment_2_1");
					put(grammarAccess.getBehaviorTransitionAccess().getConditionAssignment_4(), "rule__BehaviorTransition__ConditionAssignment_4");
					put(grammarAccess.getBehaviorTransitionAccess().getDestinationStateAssignment_6(), "rule__BehaviorTransition__DestinationStateAssignment_6");
					put(grammarAccess.getBehaviorTransitionAccess().getActionBlockAssignment_7(), "rule__BehaviorTransition__ActionBlockAssignment_7");
					put(grammarAccess.getBehaviorActionBlockAccess().getContentAssignment_1(), "rule__BehaviorActionBlock__ContentAssignment_1");
					put(grammarAccess.getBehaviorActionBlockAccess().getTimeoutAssignment_3_1(), "rule__BehaviorActionBlock__TimeoutAssignment_3_1");
					put(grammarAccess.getBehaviorActionSequenceAccess().getActionsAssignment_0_0(), "rule__BehaviorActionSequence__ActionsAssignment_0_0");
					put(grammarAccess.getBehaviorActionSequenceAccess().getActionsAssignment_1(), "rule__BehaviorActionSequence__ActionsAssignment_1");
					put(grammarAccess.getBehaviorActionSetAccess().getActionsAssignment_0_0(), "rule__BehaviorActionSet__ActionsAssignment_0_0");
					put(grammarAccess.getBehaviorActionSetAccess().getActionsAssignment_1(), "rule__BehaviorActionSet__ActionsAssignment_1");
					put(grammarAccess.getAssignmentActionAccess().getTargetAssignment_0(), "rule__AssignmentAction__TargetAssignment_0");
					put(grammarAccess.getAssignmentActionAccess().getValueExpressionAssignment_2_0(), "rule__AssignmentAction__ValueExpressionAssignment_2_0");
					put(grammarAccess.getAssignmentActionAccess().getValueExpressionAssignment_2_1(), "rule__AssignmentAction__ValueExpressionAssignment_2_1");
					put(grammarAccess.getCommunicationActionAccess().getQualifiedNameAssignment_0_0(), "rule__CommunicationAction__QualifiedNameAssignment_0_0");
					put(grammarAccess.getCommunicationActionAccess().getParametersAssignment_0_2_1(), "rule__CommunicationAction__ParametersAssignment_0_2_1");
					put(grammarAccess.getCommunicationActionAccess().getParametersAssignment_0_2_2_1(), "rule__CommunicationAction__ParametersAssignment_0_2_2_1");
					put(grammarAccess.getCommunicationActionAccess().getReferenceAssignment_1_0(), "rule__CommunicationAction__ReferenceAssignment_1_0");
					put(grammarAccess.getCommunicationActionAccess().getTargetAssignment_1_1_0_1_1(), "rule__CommunicationAction__TargetAssignment_1_1_0_1_1");
					put(grammarAccess.getCommunicationActionAccess().getParametersAssignment_1_1_4_1_1(), "rule__CommunicationAction__ParametersAssignment_1_1_4_1_1");
					put(grammarAccess.getCommunicationActionAccess().getParametersAssignment_1_1_4_1_2_1(), "rule__CommunicationAction__ParametersAssignment_1_1_4_1_2_1");
					put(grammarAccess.getCommunicationActionAccess().getTargetAssignment_1_1_5_1_1(), "rule__CommunicationAction__TargetAssignment_1_1_5_1_1");
					put(grammarAccess.getCommunicationActionAccess().getParametersAssignment_1_1_6_1_1(), "rule__CommunicationAction__ParametersAssignment_1_1_6_1_1");
					put(grammarAccess.getCommunicationActionAccess().getParametersAssignment_1_1_6_1_2_1(), "rule__CommunicationAction__ParametersAssignment_1_1_6_1_2_1");
					put(grammarAccess.getQualifiedNamedElementAccess().getBaNamespaceAssignment_0(), "rule__QualifiedNamedElement__BaNamespaceAssignment_0");
					put(grammarAccess.getQualifiedNamedElementAccess().getBaNameAssignment_1(), "rule__QualifiedNamedElement__BaNameAssignment_1");
					put(grammarAccess.getQualifiedIndentifierAccess().getIdAssignment(), "rule__QualifiedIndentifier__IdAssignment");
					put(grammarAccess.getIdentifierAccess().getIdAssignment(), "rule__Identifier__IdAssignment");
					put(grammarAccess.getReferenceAccess().getIdsAssignment_0(), "rule__Reference__IdsAssignment_0");
					put(grammarAccess.getReferenceAccess().getIdsAssignment_1_1(), "rule__Reference__IdsAssignment_1_1");
					put(grammarAccess.getArrayIdentifierAccess().getIdAssignment_0(), "rule__ArrayIdentifier__IdAssignment_0");
					put(grammarAccess.getArrayIdentifierAccess().getArrayIndexesAssignment_1_1(), "rule__ArrayIdentifier__ArrayIndexesAssignment_1_1");
					put(grammarAccess.getTimedActionAccess().getLowerTimeAssignment_2(), "rule__TimedAction__LowerTimeAssignment_2");
					put(grammarAccess.getTimedActionAccess().getUpperTimeAssignment_3_1(), "rule__TimedAction__UpperTimeAssignment_3_1");
					put(grammarAccess.getTimedActionAccess().getProcessorClassifierAssignment_5_2(), "rule__TimedAction__ProcessorClassifierAssignment_5_2");
					put(grammarAccess.getTimedActionAccess().getProcessorClassifierAssignment_5_3_1(), "rule__TimedAction__ProcessorClassifierAssignment_5_3_1");
					put(grammarAccess.getIfStatementAccess().getLogicalValueExpressionAssignment_2(), "rule__IfStatement__LogicalValueExpressionAssignment_2");
					put(grammarAccess.getIfStatementAccess().getBehaviorActionsAssignment_4(), "rule__IfStatement__BehaviorActionsAssignment_4");
					put(grammarAccess.getIfStatementAccess().getElseStatementAssignment_5_0(), "rule__IfStatement__ElseStatementAssignment_5_0");
					put(grammarAccess.getIfStatementAccess().getElseStatementAssignment_5_1(), "rule__IfStatement__ElseStatementAssignment_5_1");
					put(grammarAccess.getElseIfStatementAccess().getElifAssignment_0(), "rule__ElseIfStatement__ElifAssignment_0");
					put(grammarAccess.getElseIfStatementAccess().getLogicalValueExpressionAssignment_2(), "rule__ElseIfStatement__LogicalValueExpressionAssignment_2");
					put(grammarAccess.getElseIfStatementAccess().getBehaviorActionsAssignment_4(), "rule__ElseIfStatement__BehaviorActionsAssignment_4");
					put(grammarAccess.getElseStatementAccess().getBehaviorActionsAssignment_1(), "rule__ElseStatement__BehaviorActionsAssignment_1");
					put(grammarAccess.getForOrForAllStatementAccess().getForAllAssignment_0_1(), "rule__ForOrForAllStatement__ForAllAssignment_0_1");
					put(grammarAccess.getForOrForAllStatementAccess().getIterativeVariableAssignment_2(), "rule__ForOrForAllStatement__IterativeVariableAssignment_2");
					put(grammarAccess.getForOrForAllStatementAccess().getIteratedValuesAssignment_4(), "rule__ForOrForAllStatement__IteratedValuesAssignment_4");
					put(grammarAccess.getForOrForAllStatementAccess().getBehaviorActionsAssignment_7(), "rule__ForOrForAllStatement__BehaviorActionsAssignment_7");
					put(grammarAccess.getIterativeVariableAccess().getNameAssignment_0(), "rule__IterativeVariable__NameAssignment_0");
					put(grammarAccess.getIterativeVariableAccess().getDataClassifierAssignment_2(), "rule__IterativeVariable__DataClassifierAssignment_2");
					put(grammarAccess.getWhileOrDoUntilStatementAccess().getLogicalValueExpressionAssignment_0_2(), "rule__WhileOrDoUntilStatement__LogicalValueExpressionAssignment_0_2");
					put(grammarAccess.getWhileOrDoUntilStatementAccess().getBehaviorActionsAssignment_0_5(), "rule__WhileOrDoUntilStatement__BehaviorActionsAssignment_0_5");
					put(grammarAccess.getWhileOrDoUntilStatementAccess().getDoUntilAssignment_1_0(), "rule__WhileOrDoUntilStatement__DoUntilAssignment_1_0");
					put(grammarAccess.getWhileOrDoUntilStatementAccess().getBehaviorActionsAssignment_1_1(), "rule__WhileOrDoUntilStatement__BehaviorActionsAssignment_1_1");
					put(grammarAccess.getWhileOrDoUntilStatementAccess().getLogicalValueExpressionAssignment_1_4(), "rule__WhileOrDoUntilStatement__LogicalValueExpressionAssignment_1_4");
					put(grammarAccess.getValueExpressionAccess().getRelationsAssignment_0(), "rule__ValueExpression__RelationsAssignment_0");
					put(grammarAccess.getValueExpressionAccess().getLogicalOperatorsAssignment_1_0(), "rule__ValueExpression__LogicalOperatorsAssignment_1_0");
					put(grammarAccess.getValueExpressionAccess().getRelationsAssignment_1_1(), "rule__ValueExpression__RelationsAssignment_1_1");
					put(grammarAccess.getRelationAccess().getFirstExpressionAssignment_0(), "rule__Relation__FirstExpressionAssignment_0");
					put(grammarAccess.getRelationAccess().getRelationalOperatorAssignment_1_0(), "rule__Relation__RelationalOperatorAssignment_1_0");
					put(grammarAccess.getRelationAccess().getSecondExpressionAssignment_1_1(), "rule__Relation__SecondExpressionAssignment_1_1");
					put(grammarAccess.getSimpleExpressionAccess().getUnaryAddingOperatorAssignment_0(), "rule__SimpleExpression__UnaryAddingOperatorAssignment_0");
					put(grammarAccess.getSimpleExpressionAccess().getTermsAssignment_1(), "rule__SimpleExpression__TermsAssignment_1");
					put(grammarAccess.getSimpleExpressionAccess().getBinaryAddingOperatorsAssignment_2_0(), "rule__SimpleExpression__BinaryAddingOperatorsAssignment_2_0");
					put(grammarAccess.getSimpleExpressionAccess().getTermsAssignment_2_1(), "rule__SimpleExpression__TermsAssignment_2_1");
					put(grammarAccess.getTermAccess().getFactorsAssignment_0(), "rule__Term__FactorsAssignment_0");
					put(grammarAccess.getTermAccess().getMultiplyingOperatorsAssignment_1_0(), "rule__Term__MultiplyingOperatorsAssignment_1_0");
					put(grammarAccess.getTermAccess().getFactorsAssignment_1_1(), "rule__Term__FactorsAssignment_1_1");
					put(grammarAccess.getFactorAccess().getFirstValueAssignment_0_0(), "rule__Factor__FirstValueAssignment_0_0");
					put(grammarAccess.getFactorAccess().getBinaryNumericOperatorAssignment_0_1_0(), "rule__Factor__BinaryNumericOperatorAssignment_0_1_0");
					put(grammarAccess.getFactorAccess().getSecondValueAssignment_0_1_1(), "rule__Factor__SecondValueAssignment_0_1_1");
					put(grammarAccess.getFactorAccess().getUnaryNumericOperatorAssignment_1_0(), "rule__Factor__UnaryNumericOperatorAssignment_1_0");
					put(grammarAccess.getFactorAccess().getFirstValueAssignment_1_1(), "rule__Factor__FirstValueAssignment_1_1");
					put(grammarAccess.getFactorAccess().getUnaryBooleanOperatorAssignment_2_0(), "rule__Factor__UnaryBooleanOperatorAssignment_2_0");
					put(grammarAccess.getFactorAccess().getFirstValueAssignment_2_1(), "rule__Factor__FirstValueAssignment_2_1");
					put(grammarAccess.getBehaviorStringLiteralAccess().getValueAssignment(), "rule__BehaviorStringLiteral__ValueAssignment");
					put(grammarAccess.getBehaviorNumericLiteralAccess().getValueAssignment_1(), "rule__BehaviorNumericLiteral__ValueAssignment_1");
					put(grammarAccess.getBehaviorBooleanLiteralAccess().getValueAssignment_1_0(), "rule__BehaviorBooleanLiteral__ValueAssignment_1_0");
					put(grammarAccess.getPropertyReferenceAccess().getPropertySetAssignment_0_0_0(), "rule__PropertyReference__PropertySetAssignment_0_0_0");
					put(grammarAccess.getPropertyReferenceAccess().getQualifiedNameAssignment_0_1_0_0(), "rule__PropertyReference__QualifiedNameAssignment_0_1_0_0");
					put(grammarAccess.getPropertyReferenceAccess().getReferenceAssignment_0_1_0_1(), "rule__PropertyReference__ReferenceAssignment_0_1_0_1");
					put(grammarAccess.getPropertyReferenceAccess().getPropertyNamesAssignment_1(), "rule__PropertyReference__PropertyNamesAssignment_1");
					put(grammarAccess.getPropertyReferenceAccess().getPropertyNamesAssignment_2_1(), "rule__PropertyReference__PropertyNamesAssignment_2_1");
					put(grammarAccess.getPropertyNameAccess().getPropertyNameAssignment_0(), "rule__PropertyName__PropertyNameAssignment_0");
					put(grammarAccess.getPropertyNameAccess().getIndexesAssignment_1_0_1(), "rule__PropertyName__IndexesAssignment_1_0_1");
					put(grammarAccess.getIntegerRangeAccess().getLowerIntegerValueAssignment_0(), "rule__IntegerRange__LowerIntegerValueAssignment_0");
					put(grammarAccess.getIntegerRangeAccess().getUpperIntegerValueAssignment_2(), "rule__IntegerRange__UpperIntegerValueAssignment_2");
					put(grammarAccess.getBehaviorIntegerLiteralAccess().getValueAssignment(), "rule__BehaviorIntegerLiteral__ValueAssignment");
					put(grammarAccess.getBehaviorTimeAccess().getIntegerValueAssignment_0(), "rule__BehaviorTime__IntegerValueAssignment_0");
					put(grammarAccess.getBehaviorTimeAccess().getUnitAssignment_1(), "rule__BehaviorTime__UnitAssignment_1");
					put(grammarAccess.getDispatchConditionAccess().getDispatchTriggerConditionAssignment_3_0(), "rule__DispatchCondition__DispatchTriggerConditionAssignment_3_0");
					put(grammarAccess.getDispatchConditionAccess().getDispatchTriggerConditionAssignment_3_1(), "rule__DispatchCondition__DispatchTriggerConditionAssignment_3_1");
					put(grammarAccess.getDispatchConditionAccess().getDispatchTriggerConditionAssignment_3_2(), "rule__DispatchCondition__DispatchTriggerConditionAssignment_3_2");
					put(grammarAccess.getDispatchConditionAccess().getDispatchTriggerConditionAssignment_3_3(), "rule__DispatchCondition__DispatchTriggerConditionAssignment_3_3");
					put(grammarAccess.getDispatchConditionAccess().getFrozenPortsAssignment_4_2(), "rule__DispatchCondition__FrozenPortsAssignment_4_2");
					put(grammarAccess.getDispatchConditionAccess().getFrozenPortsAssignment_4_3_1(), "rule__DispatchCondition__FrozenPortsAssignment_4_3_1");
					put(grammarAccess.getCompletionRelativeTimeoutCatchAccess().getIntegerValueAssignment_1(), "rule__CompletionRelativeTimeoutCatch__IntegerValueAssignment_1");
					put(grammarAccess.getCompletionRelativeTimeoutCatchAccess().getUnitAssignment_2(), "rule__CompletionRelativeTimeoutCatch__UnitAssignment_2");
					put(grammarAccess.getFrozenPortsAccess().getElementAssignment(), "rule__FrozenPorts__ElementAssignment");
					put(grammarAccess.getDispatchTriggerLogicalExpressionAccess().getDispatchConjunctionsAssignment_0(), "rule__DispatchTriggerLogicalExpression__DispatchConjunctionsAssignment_0");
					put(grammarAccess.getDispatchTriggerLogicalExpressionAccess().getDispatchConjunctionsAssignment_1_1(), "rule__DispatchTriggerLogicalExpression__DispatchConjunctionsAssignment_1_1");
					put(grammarAccess.getDispatchConjunctionAccess().getDispatchTriggersAssignment_0(), "rule__DispatchConjunction__DispatchTriggersAssignment_0");
					put(grammarAccess.getDispatchConjunctionAccess().getDispatchTriggersAssignment_1_1(), "rule__DispatchConjunction__DispatchTriggersAssignment_1_1");
					put(grammarAccess.getContainedPropertyAssociationAccess().getPropertyAssignment_0(), "rule__ContainedPropertyAssociation__PropertyAssignment_0");
					put(grammarAccess.getContainedPropertyAssociationAccess().getAppendAssignment_1_1(), "rule__ContainedPropertyAssociation__AppendAssignment_1_1");
					put(grammarAccess.getContainedPropertyAssociationAccess().getConstantAssignment_2(), "rule__ContainedPropertyAssociation__ConstantAssignment_2");
					put(grammarAccess.getContainedPropertyAssociationAccess().getOwnedValueAssignment_3_0(), "rule__ContainedPropertyAssociation__OwnedValueAssignment_3_0");
					put(grammarAccess.getContainedPropertyAssociationAccess().getOwnedValueAssignment_3_1_1(), "rule__ContainedPropertyAssociation__OwnedValueAssignment_3_1_1");
					put(grammarAccess.getContainedPropertyAssociationAccess().getAppliesToAssignment_4_2(), "rule__ContainedPropertyAssociation__AppliesToAssignment_4_2");
					put(grammarAccess.getContainedPropertyAssociationAccess().getAppliesToAssignment_4_3_1(), "rule__ContainedPropertyAssociation__AppliesToAssignment_4_3_1");
					put(grammarAccess.getContainedPropertyAssociationAccess().getInBindingAssignment_5_3(), "rule__ContainedPropertyAssociation__InBindingAssignment_5_3");
					put(grammarAccess.getPropertyAssociationAccess().getPropertyAssignment_0(), "rule__PropertyAssociation__PropertyAssignment_0");
					put(grammarAccess.getPropertyAssociationAccess().getAppendAssignment_1_1(), "rule__PropertyAssociation__AppendAssignment_1_1");
					put(grammarAccess.getPropertyAssociationAccess().getConstantAssignment_2(), "rule__PropertyAssociation__ConstantAssignment_2");
					put(grammarAccess.getPropertyAssociationAccess().getOwnedValueAssignment_3_0(), "rule__PropertyAssociation__OwnedValueAssignment_3_0");
					put(grammarAccess.getPropertyAssociationAccess().getOwnedValueAssignment_3_1_1(), "rule__PropertyAssociation__OwnedValueAssignment_3_1_1");
					put(grammarAccess.getPropertyAssociationAccess().getInBindingAssignment_4_3(), "rule__PropertyAssociation__InBindingAssignment_4_3");
					put(grammarAccess.getBasicPropertyAssociationAccess().getPropertyAssignment_0(), "rule__BasicPropertyAssociation__PropertyAssignment_0");
					put(grammarAccess.getBasicPropertyAssociationAccess().getOwnedValueAssignment_2(), "rule__BasicPropertyAssociation__OwnedValueAssignment_2");
					put(grammarAccess.getContainmentPathAccess().getPathAssignment(), "rule__ContainmentPath__PathAssignment");
					put(grammarAccess.getModalPropertyValueAccess().getOwnedValueAssignment_0(), "rule__ModalPropertyValue__OwnedValueAssignment_0");
					put(grammarAccess.getModalPropertyValueAccess().getInModeAssignment_4(), "rule__ModalPropertyValue__InModeAssignment_4");
					put(grammarAccess.getModalPropertyValueAccess().getInModeAssignment_5_1(), "rule__ModalPropertyValue__InModeAssignment_5_1");
					put(grammarAccess.getOptionalModalPropertyValueAccess().getOwnedValueAssignment_0(), "rule__OptionalModalPropertyValue__OwnedValueAssignment_0");
					put(grammarAccess.getOptionalModalPropertyValueAccess().getInModeAssignment_1_3(), "rule__OptionalModalPropertyValue__InModeAssignment_1_3");
					put(grammarAccess.getOptionalModalPropertyValueAccess().getInModeAssignment_1_4_1(), "rule__OptionalModalPropertyValue__InModeAssignment_1_4_1");
					put(grammarAccess.getPropertyValueAccess().getOwnedValueAssignment(), "rule__PropertyValue__OwnedValueAssignment");
					put(grammarAccess.getLiteralorReferenceTermAccess().getNamedValueAssignment(), "rule__LiteralorReferenceTerm__NamedValueAssignment");
					put(grammarAccess.getBooleanLiteralAccess().getValueAssignment_1_0(), "rule__BooleanLiteral__ValueAssignment_1_0");
					put(grammarAccess.getConstantValueAccess().getNamedValueAssignment(), "rule__ConstantValue__NamedValueAssignment");
					put(grammarAccess.getReferenceTermAccess().getPathAssignment_2(), "rule__ReferenceTerm__PathAssignment_2");
					put(grammarAccess.getRecordTermAccess().getOwnedFieldValueAssignment_1(), "rule__RecordTerm__OwnedFieldValueAssignment_1");
					put(grammarAccess.getOldRecordTermAccess().getOwnedFieldValueAssignment_1(), "rule__OldRecordTerm__OwnedFieldValueAssignment_1");
					put(grammarAccess.getComputedTermAccess().getFunctionAssignment_2(), "rule__ComputedTerm__FunctionAssignment_2");
					put(grammarAccess.getComponentClassifierTermAccess().getClassifierAssignment_2(), "rule__ComponentClassifierTerm__ClassifierAssignment_2");
					put(grammarAccess.getListTermAccess().getOwnedListElementAssignment_2_0(), "rule__ListTerm__OwnedListElementAssignment_2_0");
					put(grammarAccess.getListTermAccess().getOwnedListElementAssignment_2_1_1(), "rule__ListTerm__OwnedListElementAssignment_2_1_1");
					put(grammarAccess.getFieldPropertyAssociationAccess().getPropertyAssignment_0(), "rule__FieldPropertyAssociation__PropertyAssignment_0");
					put(grammarAccess.getFieldPropertyAssociationAccess().getOwnedValueAssignment_2(), "rule__FieldPropertyAssociation__OwnedValueAssignment_2");
					put(grammarAccess.getContainmentPathElementAccess().getNamedElementAssignment_0_0(), "rule__ContainmentPathElement__NamedElementAssignment_0_0");
					put(grammarAccess.getContainmentPathElementAccess().getArrayRangeAssignment_0_1(), "rule__ContainmentPathElement__ArrayRangeAssignment_0_1");
					put(grammarAccess.getContainmentPathElementAccess().getPathAssignment_1_1(), "rule__ContainmentPathElement__PathAssignment_1_1");
					put(grammarAccess.getStringTermAccess().getValueAssignment(), "rule__StringTerm__ValueAssignment");
					put(grammarAccess.getArrayRangeAccess().getLowerBoundAssignment_2(), "rule__ArrayRange__LowerBoundAssignment_2");
					put(grammarAccess.getArrayRangeAccess().getUpperBoundAssignment_3_1(), "rule__ArrayRange__UpperBoundAssignment_3_1");
					put(grammarAccess.getSignedConstantAccess().getOpAssignment_0(), "rule__SignedConstant__OpAssignment_0");
					put(grammarAccess.getSignedConstantAccess().getOwnedPropertyExpressionAssignment_1(), "rule__SignedConstant__OwnedPropertyExpressionAssignment_1");
					put(grammarAccess.getIntegerTermAccess().getValueAssignment_0(), "rule__IntegerTerm__ValueAssignment_0");
					put(grammarAccess.getIntegerTermAccess().getUnitAssignment_1(), "rule__IntegerTerm__UnitAssignment_1");
					put(grammarAccess.getRealTermAccess().getValueAssignment_0(), "rule__RealTerm__ValueAssignment_0");
					put(grammarAccess.getRealTermAccess().getUnitAssignment_1(), "rule__RealTerm__UnitAssignment_1");
					put(grammarAccess.getNumericRangeTermAccess().getMinimumAssignment_0(), "rule__NumericRangeTerm__MinimumAssignment_0");
					put(grammarAccess.getNumericRangeTermAccess().getMaximumAssignment_2(), "rule__NumericRangeTerm__MaximumAssignment_2");
					put(grammarAccess.getNumericRangeTermAccess().getDeltaAssignment_3_1(), "rule__NumericRangeTerm__DeltaAssignment_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.osate.xtext.ui.contentassist.antlr.internal.InternalBaParser typedParser = (org.osate.xtext.ui.contentassist.antlr.internal.InternalBaParser) parser;
			typedParser.entryRuleAnnexSubclause();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_SL_COMMENT" };
	}
	
	public BaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
