/*
 * generated by Xtext
 */
package org.osate.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BaUiModule extends org.osate.xtext.ui.AbstractBaUiModule {
	public BaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
