/**
 * generated by Xtext
 */
package org.osate.xtext.ui.quickfix;

import org.osate.xtext.aadl2.properties.ui.quickfix.PropertiesQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
@SuppressWarnings("all")
public class BaQuickfixProvider extends PropertiesQuickfixProvider {
}
