/*
 * generated by Xtext
 */
package org.osate.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.IOutlineNode ;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider ;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;
import org.osate.ba.aadlba.BehaviorAnnex ;
import org.osate.ba.aadlba.BehaviorVariable ;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
public class BaOutlineTreeProvider extends DefaultOutlineTreeProvider
{
  
  protected void _createChildren(DocumentRootNode parentNode, BehaviorAnnex model) {
    for (BehaviorVariable bv : model.getVariables()) {
      createNode(parentNode, bv);
    }
  }
  
  protected void _createChildren(IOutlineNode parentNode, BehaviorAnnex model) {
    for (BehaviorVariable bv : model.getVariables()) {
      createNode(parentNode, bv);
    }
    super._createChildren(parentNode, model);
  }
  
}
