/*
 * generated by Xtext
 */
package org.osate.xtext.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractBaJavaValidator extends org.osate.xtext.aadl2.properties.validation.PropertiesJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("https://github.com/osate/osate2-ba.git/aadlba"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("https://github.com/osate/osate2-ba.git/declarative"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://aadl.info/AADL/2.0"));
		return result;
	}

}
