/*
 * generated by Xtext
 */
package org.osate.xtext;

import org.eclipse.xtext.linking.impl.Linker;
import org.eclipse.xtext.resource.DerivedStateAwareResource ;
import org.eclipse.xtext.resource.DerivedStateAwareResourceDescriptionManager ;
import org.eclipse.xtext.resource.IDerivedStateComputer ;
import org.eclipse.xtext.resource.IResourceDescription ;
import org.eclipse.xtext.resource.XtextResource ;
import org.osate.xtext.ba.BaDerivedStateComputer;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BaRuntimeModule extends org.osate.xtext.AbstractBaRuntimeModule {


  public Class<? extends IDerivedStateComputer> bindIDerivedStateComputer() {
    return BaDerivedStateComputer.class;
  }

  @Override
  public Class<? extends XtextResource> bindXtextResource() {
    return DerivedStateAwareResource.class;
  }

  
  public Class<? extends IResourceDescription.Manager>
                         bindIResourceDescriptionManager() {
    return DerivedStateAwareResourceDescriptionManager.class;
  }
  
//  @Override
//  public Class<? extends Linker> bindILinker()
//  {
//	  return BaLinker.class;
//  }
  
  
}
