/*
 * generated by Xtext
 */
package org.osate.xtext;

import org.osate.xtext.BaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BaStandaloneSetup extends BaStandaloneSetupGenerated{

	public static void doSetup() {
		new BaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

